### ISSUE TITLE
This package has a hard dependency to Eslint v7.29.0(+)

### ISSUE THREAD

**Issue by sjuvonen** [AtomLinter/linter-eslint-node#27]
I was running this plugin and working on a codebase where we had installed `eslint:7:24.0`. According to the package documentation we can safely use this plugin with any `eslint >=7.0.0`.

However, I was faced with the following error message in Atom: `eslint.eslintLint.getRulesMetaForResults is not a function`. 

So, I looked up this method in Eslint's sources and it seems that it has been added in version `7.29.0`, hence making it the minimum supported version.

[See the commit here](https://github.com/eslint/eslint/commit/c2cd7b4a18057ca6067bdfc16de771dc5d90c0ea#diff-cb681134e1d583c87b8a91a2dfbd4de0bfe5dd84fa3ee57efb5028d7bfeb5219R522)

I've now upgraded to `eslint:7.32.0` and everything seem to be working so far, so I cannot comment on whether or not there could be further breakage if I was actually trying to use version 7.29.0

**Comment by sjuvonen** [comment]
Tbh this requirement hardly makes this package "compatible with v7", so I would just drop that nonsense and instead advertise only support for v8+.

**Comment by savetheclocktower** [comment]
Thanks. I'll look into either (a) removing the assumption that `getRulesMetaForResults` is present… or (b) clarifying which versions of ESLint v7 are supported.

**Comment by savetheclocktower** [comment]
This got fixed in #28. We're not publishing to Pulsar's package repo yet, but those who installed straight from GitHub (`ppm install AtomLinter/linter-eslint-node`) will get the update, I think.
