### ISSUE TITLE
Atom sunset

### ISSUE THREAD

**Issue by UziTech** [AtomLinter/linter-eslint-node#29]
It seems GitHub has finally pulled the plug and are [sunsetting Atom](https://github.blog/2022-06-08-sunsetting-atom/).

I have been using a somewhat custom version of Atom for a while and plan on still using it for some development for a while.

Question is: Do people want linter-eslint-node to continue to get updates? or should we archive it (and the rest of the linters)?

**Comment by savetheclocktower** [comment]
That'll teach me to write a bunch of new code.

Personally, I can see myself continuing to be responsive to PRs and issues for as long as I'm still using Atom, but I probably won't try to keep my local Atom alive beyond the sunset date. I have no opinion on what should happen to the repo/extension at that time.

**Comment by scagood** [comment]
I for one will probably continue to use atom until it's inconvenient to do so, I think that the nail in the coffin would be if (probably when) the package manager disappears :thinking:

**Comment by savetheclocktower** [comment]
So the good news is that [Pulsar](https://github.com/pulsar-edit/pulsar) has appeared, and I'm impressed at the progress that they've made. I've been using it for a couple of weeks and the transition has been seamless.

Plus they've got [their own package manager](https://web.pulsar-edit.dev/).

If all that has to happen is that some URLs have to be updated in this project's GitHub Actions, then I'd be happy to continue maintaining this package for as long as I'm using Pulsar.

**Comment by UziTech** [comment]
@savetheclocktower I invited you to be a member of AtomLinter. I am going to clean up the repos at some point. Possibly even just create new organizations for pulsar packages.

**Comment by AlexWayfer** [comment]
Pulsar is good and still compatible with Atom packages. So it'd be great to move into this direction.
