### ISSUE TITLE
can't install es lint through tool and when i do it through cmd line.. it just crashes atom.

### ISSUE THREAD

**Issue by luke-lim** [AtomLinter/linter-eslint-node#30]
## Bug Checklist
- [ ] Restart Atom
- [ ] Verify the `eslint` CLI gives the proper result, while `linter-eslint-node` does not
- [ ] Paste the output of the `Linter Eslint Node: Debug` command from the Command Palette below

```
Linter Eslint Node: Debug output here
```

**Comment by scagood** [comment]
Can you include some reproduction steps?

**Comment by scagood** [comment]
@savetheclocktower can we close this too?
