### ISSUE TITLE
PPM upgrades aren't happening when installed from git

### ISSUE THREAD

**Issue by savetheclocktower** [AtomLinter/linter-eslint-node#35]
## Issue Type

Bug (though not our bug)

## Issue Description

I know exactly what's going on and have opened [an issue on PPM](https://github.com/pulsar-edit/ppm/issues/55): because our default branch is `main`, the PPM CLI fails to see the newest SHA when one runs `ppm upgrade linter-eslint-node`.

This affects anyone who installed via `ppm install AtomLinter/linter-eslint-node`, and affects users of `apm` as well.

## Workarounds

I think the fix is pretty simple on the PPM end, but another option is to rename our default branch to `master`. I don't have a strong opinion about this.

**Comment by savetheclocktower** [comment]
OK, good news is that [my PR for `ppm`](https://github.com/pulsar-edit/ppm/pull/56) landed and should go out in the next Pulsar release, so I don't think this is worth working around on our end.

**Comment by savetheclocktower** [comment]
[Pulsar v1.102.0 is out](https://github.com/pulsar-edit/pulsar/releases/tag/v1.102.0), so anyone who uses `linter-eslint-node` via Pulsar should make sure to download it (since auto-updates aren't working yet). I'll wait to close this until the next time we land something to `main` so I can be absolutely sure that this is fixed.

**Comment by scagood** [comment]
@savetheclocktower is this resolved now?

**Comment by savetheclocktower** [comment]
I'm pretty sure it is. If I'm wrong, I'll re-open it after the next update.
